import fs from "node:fs/promises";
import path from "node:path";
import { spawn } from "node:child_process";
import { getProjectDir, readEvents } from "@/lib/workspace/fs";
import { ensureTicketsIndex } from "@/lib/workspace/tickets";
import type { OlympusEvent } from "@/lib/schemas/events";

export type OpenInZedResult = {
  workspacePath: string;
  zedSettingsPath: string;
  acpEntrypointPath: string;
  ticketsIndexReady: boolean;
  ticketsCount: number;
  zedLaunched: boolean;
  launchError?: string;
  recentFiles: string[];
};

const DEFAULT_RECENT_FILES_CAP = 5;
const MAX_RECENT_FILES_CAP = 20;

// reads OLYMPUS_ZED_RECENT_FILES and clamps to [0, MAX_RECENT_FILES_CAP].
// invalid / unset values fall back to DEFAULT_RECENT_FILES_CAP.
function resolveRecentFilesCap(): number {
  const raw = process.env.OLYMPUS_ZED_RECENT_FILES;
  if (raw === undefined || raw === "") return DEFAULT_RECENT_FILES_CAP;
  const parsed = Number.parseInt(raw, 10);
  if (!Number.isFinite(parsed) || parsed < 0) return DEFAULT_RECENT_FILES_CAP;
  return Math.min(parsed, MAX_RECENT_FILES_CAP);
}

// extracts a workspace-relative file path from any event that carries one.
// per the "any files" spec we include source.written, artifact.written,
// file.edit, and incident.opened. other kinds without a path are skipped.
function eventPath(event: OlympusEvent): string | null {
  switch (event.kind) {
    case "source.written":
    case "artifact.written":
    case "file.edit":
      return event.path;
    case "incident.opened":
      return event.path ?? null;
    default:
      return null;
  }
}

// walks events.ndjson newest-first, collecting unique workspace-relative
// paths. paths are verified to exist on disk so renames/deletes don't make
// Zed open ghost tabs. returns absolute paths, ready for spawn().
async function collectRecentFiles(
  projectId: string,
  cap: number,
): Promise<string[]> {
  if (cap <= 0) return [];

  const events = await readEvents(projectId);
  const workspacePath = getProjectDir(projectId);
  const seen = new Set<string>();
  const absolutes: string[] = [];

  for (let i = events.length - 1; i >= 0 && absolutes.length < cap; i -= 1) {
    const rel = eventPath(events[i]);
    if (!rel) continue;

    // normalize separators and drop leading slashes so join() stays inside
    // the workspace dir. guard against any path escaping via '..' segments.
    const normalized = rel.replace(/\\+/g, "/").replace(/^\/+/, "");
    if (!normalized || normalized.includes("..")) continue;
    if (seen.has(normalized)) continue;
    seen.add(normalized);

    const absolute = path.resolve(workspacePath, normalized);
    if (!absolute.startsWith(workspacePath)) continue;

    try {
      const stat = await fs.stat(absolute);
      if (!stat.isFile()) continue;
    } catch {
      continue;
    }

    absolutes.push(absolute);
  }

  return absolutes;
}

// absolute path candidates (from this web app's cwd) for the real ACP server
// entrypoint. the first one that exists becomes the target of the .zed/ shim.
const ACP_DIST_CANDIDATES = [
  "olympus-agents/dist/main.js",
  "olympus-agents/bin/olympus-acp-server.cjs",
];

function acpPlaceholder(): string {
  return `#!/usr/bin/env node
// Placeholder Olympus ACP server entrypoint.
// Replace by building the @olympus/acp-server package (see olympus-agents/).
process.stderr.write(
  'olympus-acp-server placeholder: ACP package not yet built. ' +
    'Run \`pnpm --filter @olympus/acp-server build\` from the repo root.\\n',
);
process.exit(1);
`;
}

async function resolveAcpSource(): Promise<string | null> {
  for (const candidate of ACP_DIST_CANDIDATES) {
    const abs = path.resolve(process.cwd(), candidate);
    try {
      await fs.access(abs);
      return abs;
    } catch {
      // try next
    }
  }
  return null;
}

// the shim lives inside the project's .zed/ dir; it just requires the real
// ACP server via an absolute path so Zed's agent_servers entry stays stable
// even if the user moves the workspace.
function buildAcpShim(absoluteSourcePath: string): string {
  const requireTarget = JSON.stringify(absoluteSourcePath);
  return `#!/usr/bin/env node
// Auto-generated by Olympus "Open in Zed". Delegates to the real ACP server.
try {
  require(${requireTarget});
} catch (error) {
  process.stderr.write(
    'olympus-acp-server: failed to load ' + ${requireTarget} + '\\n',
  );
  process.stderr.write(String(error && error.stack || error) + '\\n');
  process.exit(1);
}
`;
}

async function writeAcpEntrypoint(zedDir: string): Promise<string> {
  const target = path.join(zedDir, "olympus-acp-server.cjs");
  const source = await resolveAcpSource();
  const contents = source ? buildAcpShim(source) : acpPlaceholder();
  await fs.writeFile(target, contents, "utf8");
  await fs.chmod(target, 0o755).catch(() => {});
  return target;
}

function buildZedSettings(params: {
  projectId: string;
  workspacePath: string;
  acpEntrypointPath: string;
  olympusApi: string;
}): string {
  const envPassthrough: Record<string, string> = {
    OLYMPUS_PROJECT_ID: params.projectId,
    OLYMPUS_WORKSPACE: params.workspacePath,
    OLYMPUS_API: params.olympusApi,
  };

  for (const key of [
    "OPENROUTER_API_KEY",
    "OPENROUTER_BASE_URL",
    "LLM_PROVIDER",
    "MODEL_TIER_FAST",
    "MODEL_TIER_REASONING",
    "MODEL_TIER_CODING",
    "MODEL_TIER_VISION",
  ]) {
    const value = process.env[key];
    if (value) envPassthrough[key] = value;
  }

  const settings = {
    agent_servers: {
      Olympus: {
        command: "node",
        args: [params.acpEntrypointPath],
        env: envPassthrough,
      },
    },
  };

  return `${JSON.stringify(settings, null, 2)}\n`;
}

async function tryLaunchZed(
  workspacePath: string,
  extraFiles: string[] = [],
): Promise<{ ok: boolean; error?: string }> {
  if (process.env.OLYMPUS_SKIP_ZED_LAUNCH === "1") {
    return { ok: false, error: "launch skipped (OLYMPUS_SKIP_ZED_LAUNCH=1)" };
  }

  const args = [workspacePath, ...extraFiles];

  return new Promise((resolve) => {
    try {
      const child = spawn("zed", args, {
        detached: true,
        stdio: "ignore",
      });
      child.once("error", (err) => {
        resolve({ ok: false, error: err.message });
      });
      child.unref();
      setTimeout(() => resolve({ ok: true }), 150);
    } catch (err) {
      resolve({
        ok: false,
        error: err instanceof Error ? err.message : String(err),
      });
    }
  });
}

export type FocusFileResult = {
  ok: boolean;
  error?: string;
};

// opens or focuses a specific file in the already-running Zed workspace.
// `zed <path>:<line>` reuses the existing window without opening a new instance.
export async function focusFileInZed(
  projectId: string,
  relativePath: string,
  line = 1,
): Promise<FocusFileResult> {
  if (process.env.OLYMPUS_SKIP_ZED_LAUNCH === "1") {
    return {
      ok: false,
      error: "zed focus skipped (OLYMPUS_SKIP_ZED_LAUNCH=1)",
    };
  }

  const workspacePath = getProjectDir(projectId);
  const absolutePath = path.resolve(workspacePath, relativePath);

  return new Promise((resolve) => {
    try {
      const child = spawn("zed", [`${absolutePath}:${line}`], {
        detached: true,
        stdio: "ignore",
      });
      child.once("error", (err) => {
        resolve({ ok: false, error: err.message });
      });
      child.unref();
      setTimeout(() => resolve({ ok: true }), 100);
    } catch (err) {
      resolve({
        ok: false,
        error: err instanceof Error ? err.message : String(err),
      });
    }
  });
}

export async function openProjectInZed(
  projectId: string,
): Promise<OpenInZedResult> {
  const workspacePath = getProjectDir(projectId);
  await fs.access(workspacePath);

  const zedDir = path.join(workspacePath, ".zed");
  await fs.mkdir(zedDir, { recursive: true });

  const ticketsIndex = await ensureTicketsIndex(projectId);
  const acpEntrypointPath = await writeAcpEntrypoint(zedDir);

  const webPort = process.env.OLYMPUS_WEB_PORT ?? "3100";
  const settings = buildZedSettings({
    projectId,
    workspacePath,
    acpEntrypointPath,
    olympusApi: `http://localhost:${webPort}/api`,
  });
  const zedSettingsPath = path.join(zedDir, "settings.json");
  await fs.writeFile(zedSettingsPath, settings, "utf8");

  // surface the most recent file writes as open tabs so the editor lands on
  // what the agents last touched instead of a blank pane. pulled from the
  // persisted ndjson so it survives server restarts.
  const recentFilesCap = resolveRecentFilesCap();
  const recentFiles = await collectRecentFiles(projectId, recentFilesCap);

  const launch = await tryLaunchZed(workspacePath, recentFiles);

  return {
    workspacePath,
    zedSettingsPath,
    acpEntrypointPath,
    ticketsIndexReady: ticketsIndex !== null,
    ticketsCount: ticketsIndex?.tickets.length ?? 0,
    zedLaunched: launch.ok,
    launchError: launch.error,
    recentFiles,
  };
}
